[project]
name = "dial2vec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "sentence-transformers>=4.1.0",
    "torch>=2.7.1",
    "transformers>=4.52.4",
]
